title: Alex Ding
author: Alex Ding
email: alex.e.ding@gmail.com
url: https://Junypr.github.io
baseurl: ""
description: "Portfolio of Alex Ding, MIT '28 computer science student."

permalink:

favicon: "logo.png"

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: compressed

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

remote_theme: Junypr/no-style-please
